/**
@provable automatic
@statistic branches 11
@statistic nodes 333

 Here we want to show a case where an array store exception is indeed thrown.
The array a is of type CSub12[]. When trying to store an element of type CSub3 in it, an ASE is thrown.
*/


\javaSource "./classes";


\problem { 
   \<{ ISuper[] a = new CSub12[100];
       boolean aseThrown = false;
       try { 
          a[5] = new CSub3();
       } catch(ArrayStoreException ase) {
          aseThrown = true;
       } }\> aseThrown = TRUE
}
